### PR TITLE
:seedling: Use serviceAccountName instead of deprecated serviceAccount

### PR DESCRIPTION
**Pull request by tamalsaha**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by qiujian16** [comment]
cc @zhujian7

**Comment by zhujian7** [comment]
@tamalsaha thank you for the PR, do you know the `serviceAccountName` is introduced from which k8s version?

**Comment by tamalsaha** [comment]
Looks like 5-6 yrs ago from git blame
https://github.com/kubernetes/api/blame/master/core/v1/types.go#L3549

**Pull request merged**
