### PR TITLE
🌱 Change coverage configuration

### PR DESCRIPTION
**Pull request by xuezhaojun**
## Summary

```
Error: Codecov token not found. Please provide Codecov token with -t flag.
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

Codecov fails to report coverage for a long time.

### CODE REVIEW

**Comment by xuezhaojun** [comment]
Need to force merge this.

**Comment by zhujian7** [comment]
> Need to force merge this.

/override "codecov/project"

**Pull request merged**
