### PR TITLE
add v1beta1 managed service account

### PR DESCRIPTION
**Pull request by zhujian7**
issue reference: https://github.com/open-cluster-management-io/managed-serviceaccount/issues/77

### CODE REVIEW

**Comment by zhujian7** [comment]
I am considering moving the generated client from "pkg/generated/clientset" to "apis/generated/clientset", which opens the possibility of using the apis directory as a submodule in the future. 
@qiujian16 WDYT?

**Comment by qiujian16** [comment]
> I am considering moving the generated client from "pkg/generated/clientset" to "apis/generated/clientset", which opens the possibility of using the apis directory as a submodule in the future. @qiujian16 WDYT?

generated/clientset maybe? mostly we do not put client and type in one root directory.

**Comment by zhujian7** [comment]
> mostly we do not put client and type in one root directory.

OK, if putting client and type in one root directory is not a good practice, I'd prefer to keep it "pkg/generated/clientset"

**Pull request merged**
