### PR TITLE
add test to validate deletion of managedserviceaccount

### PR DESCRIPTION
**Pull request by TheRealHaoLiu**
related to https://github.com/open-cluster-management-io/managed-serviceaccount/issues/14

Signed-off-by: Hao Liu <haoli@redhat.com>

### CODE REVIEW

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Comment by yue9944882** [comment]
@TheRealHaoLiu can you rebase to get this in?

**Comment by TheRealHaoLiu** [comment]
rebased

**Review by yue9944882 — COMMENTED** [review]
/lgtm

**Pull request merged**
