### PR TITLE
switch health lease to primarily managed cluster side

### PR DESCRIPTION
**Pull request by TheRealHaoLiu**
Closes https://github.com/open-cluster-management-io/managed-serviceaccount/issues/15

### CODE REVIEW

**Review by qiujian16 — COMMENTED** [review]
I think it need an rbac rules to update lease.

**Comment by yue9944882** [comment]
as far as i know the the hub-side lease is required by the hub registration-controller (ref https://github.com/open-cluster-management-io/managed-serviceaccount/issues/15#issuecomment-1031058171). am i missing anything?

**Comment by TheRealHaoLiu** [comment]
@qiujian16 https://github.com/open-cluster-management-io/managed-serviceaccount/blob/main/pkg/addon/manager/addon.go#L109-L113

the addon creates a manifestwork to configure RBAC on managed cluster side and here's where it granted the lease permission

**Comment by qiujian16** [comment]
yes, you can use the lease on spoke instead of on hub.

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
