### PR TITLE
🌱  Update dependencies to k8s 1.29 client libs

### PR DESCRIPTION
**Pull request by tamalsaha**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by tamalsaha** [comment]
It compiles with Go 1.22

**Comment by qiujian16** [comment]
@xuezhaojun do you know why codecov failed? It should not have such coverage reduction.

**Comment by qiujian16** [comment]
/approve

Leave to @zhujian7 for final review

**Comment by xuezhaojun** [comment]
> @xuezhaojun do you know why codecov failed? It should not have such coverage reduction.

Agree, I'm on it.

**Comment by xuezhaojun** [comment]
@qiujian16 @tamalsaha The reason why the coverage score dropped is because go 1.22 changed its strategy and count pkg without any test file as 0.0%:

image

Source link: https://tip.golang.org/doc/go1.22

---

Expect for this change, it seems the test coverage is under other inconsistency issue as well: https://github.com/golang/go/issues/65570

---

So we suggest to use a stable 1.21 version of go instead of go 1.22.0

**Comment by tamalsaha** [comment]
> So we suggest to use a stable 1.21 version of go instead of go 1.22.0

What do mean by "stable" 1.21? GO 1.22 has been released a month ago. https://go.dev/blog/go1.22 .

**Comment by xuezhaojun** [comment]
> > So we suggest to use a stable 1.21 version of go instead of go 1.22.0
> 
> What do you mean by "stable" 1.21? GO 1.22 was released a month ago. https://go.dev/blog/go1.22 .

The 1.21.7 is good to go with.

**Comment by tamalsaha** [comment]
What is the path for go 1.22?

**Comment by tamalsaha** [comment]
Switched to GO 1.21

**Comment by xuezhaojun** [comment]
> What is the path for go 1.22? It has the compiler change for the range loop variable thing which is nice.

Agree that's a fancy feature, but that's also one of the reasons we want to postpone the upgrade until we have at least one community meeting to discuss and evaluate the impact of 1.22. I will make sure the topic goes on to the meeting agenda as soon as possible.

**Pull request merged**
