### PR TITLE
add 0.3.0 changelog and upgrade ocm api

### PR DESCRIPTION
**Pull request by ldpliu**

### CODE REVIEW

**Comment by xuezhaojun** [comment]
Do we need to update the chart version to 0.3.0 as well? https://github.com/open-cluster-management-io/managed-serviceaccount/blob/4439d50fbaaac0b70c2fc78fef0f5414f859e1fa/charts/managed-serviceaccount/Chart.yaml#L5

**Comment by qiujian16** [comment]
we should also update the PAT in this PR.

**Comment by ldpliu** [comment]
> we should also update the PAT in this PR.

done

**Comment by qiujian16** [comment]
@xuezhaojun can you take a look again. I think we also need to remove debug field here?

**Comment by xuezhaojun** [comment]
> @xuezhaojun can you take a look again. I think we also need to remove debug field here?

Agree, @ldpliu  please delete this line to get the GoRelease passed: https://github.com/open-cluster-management-io/managed-serviceaccount/blob/4439d50fbaaac0b70c2fc78fef0f5414f859e1fa/.github/workflows/go-release.yml#L122

PS: the similar PR in cluster-proxy: https://github.com/open-cluster-management-io/cluster-proxy/pull/163

**Comment by ldpliu** [comment]
> 



> > @xuezhaojun can you take a look again. I think we also need to remove debug field here?
> 
> Agree, @ldpliu please delete this line to get the GoRelease passed:
> 
> https://github.com/open-cluster-management-io/managed-serviceaccount/blob/4439d50fbaaac0b70c2fc78fef0f5414f859e1fa/.github/workflows/go-release.yml#L122
> 
> And before merge this PR, @qiujian16 please also take a look at this token update PR in helm-charts repo: [open-cluster-management-io/helm-charts#9](https://github.com/open-cluster-management-io/helm-charts/pull/9)
> 
> PS: the similar PR in cluster-proxy: [open-cluster-management-io/cluster-proxy#163](https://github.com/open-cluster-management-io/cluster-proxy/pull/163)

Thanks,
Changed
@qiujian16 Please help to review it again

**Pull request merged**
